#AlgoProfiler configuration
#Tue May 12 13:56:55 ICT 2026
ai.api.key=
ai.api.url=https\://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash\:generateContent
ai.model=gemini-1.5-flash
crawl.daily.time=13\:41
crawl.max_new_per_user=3
crawl.schedule.enabled=true
