#AlgoProfiler configuration
#Tue May 12 16:21:12 ICT 2026
ai.api.key=AIzaSyBa4SplR1lzkqsbQlKs78LM9s904E_55u0
ai.api.url=https\://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash\:generateContent
ai.model=gemini-2.5-flash
crawl.daily.time=02\:00
crawl.max_new_per_user=5
crawl.schedule.enabled=true
